### ISSUE TITLE
validateAttribute never returns the passed messages if clientValidation is false

### ISSUE THREAD

**Issue by integrafinrc** [nepstor/yii2-datetime-compare-validator#10]
In the validateAttribute there is a switch on the operator which only ever returns the default messages and not the one passed by the validator config specified.

example:

> switch ($this->operator) {
>            case '=':
>                 if ($valueDT != $compareValueDT) {
>                     $message = $this->_messages[$this->operator];
>                 }
>                 break;

This means that if you are not using clientValidation the error message is not the one you set in the config. (function clientValidateAttribuite does return the config message). I think the above (and cases like it for other operators in the same switch) should be:-

> switch ($this->operator) {
>             case '=':
>                 if ($valueDT != $compareValueDT) {
>                     $message = $this->message;
>                 }
>                 break;
> 

Sorry if I've got the wrong end of the stick here

**Comment by nepstor** [comment]
Yes you are right. Fixed, you need to upgrade to version 2.0.2
